use_frameworks!

platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'


target 'XModule_Example' do
  pod 'XModule', :path => '../'

  target 'XModule_Tests' do
    inherit! :search_paths

    
  end
end
